### ISSUE TITLE
Invalid flag in Chrome

### ISSUE THREAD

**Issue by machawk1** [internetarchive/brozzler#11]
In Chrome 52.0.2743.116 for OS X, I receive a dropbox in the browser's viewport stating that the command-line flag passed to it from Brozzler was invalid. This occurs after executing `brozzler-easy`.
![screen shot 2016-08-11 at 3 12 51 pm](https://cloud.githubusercontent.com/assets/2514780/17601449/31224008-5fd6-11e6-981e-25fb58229da0.png)

Installed brozzler using `pip3 install brozzler[easy]`.

**Comment by nlevitt** [comment]
Yep that's true, but we need that flag! 
https://github.com/internetarchive/brozzler/commit/6a5d1e2266d
