### ISSUE TITLE
`pip3 install brozzler[easy]` fails due to `warcprox>=2.4b2.dev173` requirement

### ISSUE THREAD

**Issue by malob** [internetarchive/brozzler#112]
When I run `pip3 install brozzler[easy]` I get the following error:
```
  Could not find a version that satisfies the requirement warcprox>=2.4b2.dev173 (from brozzler[easy]) (from versions: 1.0, 1.1, 1.2, 1.3, 1.4, 2.0.dev9, 2.0b1, 2.0b2, 2.0, 2.0.1, 2.1b1.dev60, 2.1b1.dev68, 2.1b1.dev71, 2.1b1.dev86, 2.1b1.dev87, 2.2, 2.3, 2.4b1)
No matching distribution found for warcprox>=2.4b2.dev173 (from brozzler[easy])
```

I checked on PyPi, and it looks like warcprox 2.4b1 is the most recent released published.

(FYI, I'm running Ubuntu 18.04, and Python 3.6.5, not that this should matter for this error.)

**Comment by malob** [comment]
FYI, I get this to install by installing the latest version of `warcprox` from [GitHub](https://github.com/internetarchive/warcprox/tree/master) first.

Thought it didn't work the first time since on of the requirements `pillow` depends on a system package `libjpeg-dev` which wasn't installed on Ubuntu 18.04.

**Comment by robert-1043** [comment]
having the same issue on Ubuntu 16.04

**Comment by nlevitt** [comment]
I pushed up a new release 2.4b2 to pypi. Does that fix it for you?

> Thought it didn't work the first time since on of the requirements pillow depends on a system package libjpeg-dev which wasn't installed on Ubuntu 18.04.

That's a normal sort of thing when installing any kind of software, no? Are you requesting we do anything about it?

**Comment by robert-1043** [comment]
yes it does: installs fine now (finds a Pillow 5.2.0 and uninstalls it)

**Comment by malob** [comment]
@nlevitt, thanks!

> That's a normal sort of thing when installing any kind of software, no? Are you requesting we do anything about it?

I actually realized that the required library is actually a dependency of Chrome, but I didn't have Chrome installed at the time.

It's not a big deal, but I do often appreciate when software projects list dependencies that are often missing on many systems. It's a lot of work to list all the different names that they might have in different packages managers / distros, so I wouldn't push for anything like that (though it's always nice when people do include that sort of thing), but some note in the installation instructions flagging a dependency is commonly missing, is always appreciated. ¯\_(ツ)_/¯

**Comment by nlevitt** [comment]
@malob I updated the pillow dependency to 5.2.0. There are binary distributions (wheels) of pillow 5.2.0, which embed libjpeg, on pypi for a lot of OS's. I think that might obviate the need for a note in the readme?

**Comment by nlevitt** [comment]
Gonna resolve this, feel free to reopen it or open a new issue
