### ISSUE TITLE
Can't start a worker

### ISSUE THREAD

**Issue by wolkix3** [internetarchive/brozzler#125]
When trying to start a worker I get this error
`  File "/home/thore/.local/bin/brozzler-worker", line 7, in <module>
    from brozzler.cli import brozzler_worker
  File "/home/thore/.local/lib/python2.7/site-packages/brozzler/__init__.py", line 70, in <module>
    logging._levelToName[TRACE] = 'TRACE'
AttributeError: 'module' object has no attribute '_levelToName'`

**Comment by anjackson** [comment]
As per [the requirements](https://github.com/internetarchive/brozzler#requirements) Brozzler needs Python >= 3.4 and you're running Python 2.7.

**Comment by wolkix3** [comment]
I'm an idiot but thanks anyways
