### ISSUE TITLE
--single-process chrome arg

### ISSUE THREAD

**Issue by ghsnd** [internetarchive/brozzler#128]
When trying to run brozzler, this line appears in the logs and chromium crashes:

```
 DEBUG ChromeOutReaderThread:37385 brozzler.chrome.Chrome._read_stderr_stdout(chrome.py:273) chrome pid 21558 STDERR b'[21558:21558:1016/150743.534943:ERROR:default_network_context_params.cc(64)] Cannot use V8 Proxy resolver in single process mode.\n'
```

Removing the hard-coded `--single-process` parameter in `brozzler/chrome.py` seems to fix the issue. Is this flag necessary for brozzler to work?

Here's some more debug info. 

```
chromium-browser --version
Chromium 69.0.3497.81 Built on Ubuntu , running on Ubuntu 18.04
```

How brozzler started chromium:

`INFO BrozzlingThread:37385 brozzler.chrome.Chrome.start(chrome.py:180) running: 'chromium-browser --remote-debugging-port=37385 --use-mock-keychain --user-data-dir=/tmp/tmp5qcy14wv/chrome-user-data --disable-background-networking --disable-renderer-backgrounding --disable-hang-monitor --disable-background-timer-throttling --mute-audio --disable-web-sockets --disable-cache --single-process --window-size=1100,900 --no-default-browser-check --disable-first-run-ui --no-first-run --homepage=about:blank --disable-direct-npapi-requests --disable-web-security --disable-notifications --disable-extensions --disable-save-password-bubble --ignore-certificate-errors --proxy-server=localhost:8888 about:blank'`

With a warcprox instance running at localhost:8888

**Comment by nlevitt** [comment]
Thanks for the report. The chromium flag was introduced by https://github.com/internetarchive/brozzler/pull/99. @vbanos do you have any thoughts, objections to reverting?

**Comment by vbanos** [comment]
This didn't happen with previous Chromium versions, it must be a new problem of Chromium 69.

No problem with removing it. It was a minor optimisation trick to reduce the number of processes running.

**Comment by nlevitt** [comment]
Removed the argument!
