### ISSUE TITLE
brozzler-stop command would be nice

### ISSUE THREAD

**Issue by detrout** [internetarchive/brozzler#32]
Hi,

I was trying to crawl https://www.ncdc.noaa.gov/sotc and for some reason it never finished I'm not sure why, I noticed there were a number of "revisit" tags in the brozzler-easy log messages and suspect it was just cycling over the same pages over and over. (I think I need to understand how to read warc files before I can confirm that though)

I found some code that referred to stop_requested, in brozzler/job.py but nothing seemed to ever set that variable to True.

I stopped the crawl by using the rethinkdb console and changing "state" to "FINISHED". I could probably figure out how to write a command that given a job id updated the variable, if that seems like a reasonable solution.

**Comment by nlevitt** [comment]
Yes it would! TODO

**Comment by nlevitt** [comment]
"revisit" means a revisit record was written to the warc, which means it points to a different warc record where the payload of the url has previously been archived, to save space. See section 6.7.2 of http://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/ in particular. It probably doesn't have any bearing on why your crawl didn't finish.

Maybe brozzler just has more pages to crawl. Try `brozzler-list-pages --queued --site=SITE_ID`? Or do you see something in the logs suggesting that the same page is being crawled repeatedly, and erroring, or something along those lines?

**Comment by nlevitt** [comment]
In case you're thinking of coding up `brozzler-stop`, I think setting `stop_requested` is a better approach than setting `status`.  One potential issue is that at the moment `stop_requested` is only supported at the job level, not the site level. It looks like it would be pretty easy to add support for `stop_requested` at the site level, but I wouldn't call that a prerequisite to merging a pull request.

**Comment by detrout** [comment]
RE brozzler-stop Ok I'll look at it a bit more and to see how stop_requested should work.

I was using the version of brozzler on pypi which didn't have list-pages I upgraded to the git version. There's actually no intersection between the list of queued pages and brozzled pages. 

Though some queued pages have a hops_from_seed count of 38 which I'm not really sure how it got that high. Also brozzler seems to be separately archiving pages with in page anchors.

For example looking around in the list produced by 
```brozzler-list-pages --site <uuid> --brozzled | grep url | sort | uniq -c | less```

There's several listed pages. I think they're all just different parts of the same page (in this sites case).

     1   "url": "https://www.ncdc.noaa.gov/sotc/drought/201208",
      1   "url": "https://www.ncdc.noaa.gov/sotc/drought/201208#contents",
      1   "url": "https://www.ncdc.noaa.gov/sotc/drought/201208#det-agri-hydro",
      1   "url": "https://www.ncdc.noaa.gov/sotc/drought/201208#detailed-discussion",
      1   "url": "https://www.ncdc.noaa.gov/sotc/drought/201208#det-hist-analog",
      1   "url": "https://www.ncdc.noaa.gov/sotc/drought/201208#det-over",
      1   "url": "https://www.ncdc.noaa.gov/sotc/drought/201208#det-pcs",
      1   "url": "https://www.ncdc.noaa.gov/sotc/drought/201208#det-pdi",
      1   "url": "https://www.ncdc.noaa.gov/sotc/drought/201208#det-pdi-pe",
      1   "url": "https://www.ncdc.noaa.gov/sotc/drought/201208#det-reg",
      1   "url": "https://www.ncdc.noaa.gov/sotc/drought/201208#det-reg-pacis",
      1   "url": "https://www.ncdc.noaa.gov/sotc/drought/201208#det-reg-rcc",
      1   "url": "https://www.ncdc.noaa.gov/sotc/drought/201208#det-spi",

**Comment by nlevitt** [comment]
Yes indeed. These days aren't just anchors within the page, they often trigger javascript stuff, including loading of different urls, etc. So it's important brozzler crawl them. The way it's handled now is not optimal though. The plan is to visit all the hash tags that have been discovered under a page url while brozzling that page.

**Comment by nlevitt** [comment]
Added `brozzler-stop-crawl` command in commit https://github.com/internetarchive/brozzler/commit/df7734f2cadfa1c8308f6a575328cc8c1ab6a041
Resolving!
