### ISSUE TITLE
brozzler[easy] not found

### ISSUE THREAD

**Issue by primoz-k** [internetarchive/brozzler#35]
Hi, I'm trying to install brozzler[easy] in my virtualenv (Python 3.5.2), but pip says that no matches were found if I run this command:

`pip install brozzler[easy]`

I have successfully installed `brozzler` (1.1b10) with pip in this virtual environment.

Complete flow:
```
primoz@computer:~/projects|⇒  pip install brozzler[easy]
zsh: no matches found: brozzler[easy]
```

And `brozler[dashboard]` is not found either.

**Comment by primoz-k** [comment]
Oh, I have found the issue and it wasn't related to this library.

The problem was with `zsh` I think. This works:

`pip install "brozzler[easy]"`

**Comment by AC304646** [comment]
Hi Guys, I have an error while installing brazeler[easy] using on Mac


Collecting cerberus<=1.0.1,>=1.0.1 (from brozzler[easy])
  Downloading Cerberus-1.0.1.tar.gz (36 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/Users/XXXX/Desktop/XXX/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()


Can any one help please?
