### ISSUE TITLE
"status_info is missing required field ttl" when running brozzle-worker

### ISSUE THREAD

**Issue by peterk** [internetarchive/brozzler#43]
Installing brozzler and running it according to the instrux does not work. The problem seems to be in the doublethink module where the following error occurs when running brozzle-worker:

```
2017-06-08 22:17:54,993 8363 CRITICAL MainThread brozzler.worker.BrozzlerWorker.run(worker.py:504) thread exiting due to unexpected exception
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/brozzler/worker.py", line 446, in _service_heartbeat
    self.status_info = self._service_registry.heartbeat(status_info)
  File "/venv/lib/python3.6/site-packages/doublethink/services.py", line 142, in heartbeat
    repr(field))
Exception: ('status_info is missing required field %s', "'ttl'")
```

The ttl field is indeed missing as the status_info dict looks like this:

```python
{'browser_pool_size': 1,
 'browsers_in_use': 0,
 'heartbeat_interval': 20.0,
 'load': 0.0,
 'role': 'brozzler-worker'}
```

The check for ttl in status_info seems to have been added in this version of doublethink:
https://github.com/internetarchive/doublethink/commit/a1c5a0879088d7b7abd79c3feb9f3fc4aaf4d880

Downgrading to doublethink 0.2.0.dev73 seems to solve the problem.

**Comment by nlevitt** [comment]
Thanks for the report @peterk. Yeah, issue is that the version of brozzler on pypi doesn't work with the latest doublethink. I pushed the latest to pypi which should fix the issue. Let me know if you still have trouble.
