### ISSUE TITLE
Rationale for using browser

### ISSUE THREAD

**Issue by KrzysztofMadejski** [internetarchive/brozzler#76]
It may a newbie question, but in README I'm missing a rationale for using browser for scraping&archiving. 

Question 1) Why you need browser in the first place?
Question 2) If it's for Javascript why not use http://phantomjs.org/ ?

**Comment by nlevitt** [comment]
1. Yes for javascript and other fancy stuff the browser does.
2. a. there is headless chrome/chromium now
    b. phantomjs maintainer stepped down when that happened --
 https://groups.google.com/forum/#!msg/phantomjs/9aI5d-LDuNE/5Z3SMZrqAQAJ
    c. is headlessness really that important? 
    d. being able to see the browser in action is very useful for debugging
    e. chrome debugging protocol is powerful and now standard way to communicate with browser (not sure how it compares to phantomjs api)
    f. phantomjs doesn't support flash

**Comment by nlevitt** [comment]
Feel free to reopen if you have more questions :)
