### ISSUE TITLE
Using WARCs with standard PyWb

### ISSUE THREAD

**Issue by thomaspreeceBBC** [internetarchive/brozzler#80]
Trying to take the WARCs saved by Warcprox, index them and play them back with standard pywb but getting some issues with some of the records inside the WARC. For example:
```
WARC/1.0^M
WARC-Type: response^M
WARC-Record-ID: <urn:uuid:c603136b-0bb2-4b94-8e49-9e7113b88e15>^M
WARC-Date: 2018-01-23T16:24:36Z^M
WARC-Target-URI: https://www.bbc.co.uk/^M
WARC-IP-Address: 212.58.244.67^M
Content-Type: application/http;msgtype=response^M
WARC-Payload-Digest: sha1:3I42H3S6NNFQ2MSVX7XZKYAYSCX5QBYJ^M
Content-Length: 377^M
WARC-Block-Digest: sha1:UXTY2PXPGPSY6C3L6QLFUDNGWMS5CU7N^M
^M
HTTP/1.1 200 OK^M
Content-Type: text/html; charset=utf-8^M
ETag: W/"434a6-QjTzOogzAHForrr8966RtzKEhqg"^M
X-Frame-Options: SAMEORIGIN^M
Content-Length: 275622^M
Date: Tue, 23 Jan 2018 16:24:35 GMT^M
Connection: keep-alive^M
X-Cache-Action: HIT^M
X-Cache-Hits: 1580^M
X-Cache-Age: 94^M
Cache-Control: private, max-age=0, must-revalidate^M
Vary: Accept-Encoding, X-CDN, X-BBC-Edge-Scheme^M
```
is one of the records in the WARC. As you can see it doesn't have a payload other then the headers. Later down in the WARC is a record for the same url that does have a payload but pywb finds this record first so shows a blank page. 
I don't really understand what is happening with the browser cache/server cache and why this request returns a 200 without a payload, any ideas? (or is this more of a warcprox question)
(I also notice that you give chrome the flag --disable-cache in the code but it's not in the list https://peter.sh/experiments/chromium-command-line-switches/ so wondering if the flag has changed and might be related to this issue?)

**Comment by nlevitt** [comment]
You're probably looking at a HEAD request. (You can verify this by inspecting the request record which follows the response in the warc.) Youtube-dl makes HEAD requests and unfortunately pywb and other wayback implementations don't have special handling for those. So what you should probably do is run warcprox with `--method-filter=GET --method-filter=POST`. This will prevent it from writing HEAD requests to the warc.

**Comment by nlevitt** [comment]
I'm gonna close this issue. Feel free to reopen if this doesn't solve the problem.

**Comment by ikreymer** [comment]
@thomaspreeceBBC 

Just to add, if you index your WARC with `cdx-indexer -p`, pywb 2.0 will index HEAD requests differently, so they should not conflict with regular get requests, eg. the key should be `com,example)/?__pywb_method=head`

This should also be happening automatically if you're using `wb-manager` to add WARCs also.
