### ISSUE TITLE
ModuleNotFoundError: No module named 'pywb.cdx'

### ISSUE THREAD

**Issue by sudonym1** [internetarchive/brozzler#86]
I am trying to install brozzler on macOS 10.13.2. After running `pip3 install brozzler[easy]`, I tried to run `brozzler-easy`, but got the following error:

> CRITICAL:root:ModuleNotFoundError: No module named 'pywb.cdx'
> 
> You might need to run "pip install brozzler[easy]".
> See README.rst for more information.

I checked and `pywb` is installed. However, it looks like the `pywb` package removed the `pywb.cdx` module at some point. Do I need to install an older version of `pywb`?

**Comment by ikreymer** [comment]
pywb 2.0 has significant changes, the dependency should probably be `pywb<2.0` until brozzler is migrated.

**Comment by nlevitt** [comment]
Yes indeed. I committed the fix for this issue about an hour before you filed it :)
https://github.com/internetarchive/brozzler/commit/5331aca33f350db3
Since then I resolved a few more dependency version problems, and pushed a new version to pypi. Does it work for you?

**Comment by sudonym1** [comment]
@nlevitt Perfect. It works now. :smile:
